"""Add invalidated column to DataBlockLog

Revision ID: acc23b0de51c
Revises: 8e9953e3605f
Create Date: 2021-02-23 18:49:21.701842

"""
import snapflow
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "acc23b0de51c"
down_revision = "8e9953e3605f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "_snapflow_data_block_log",
        sa.Column("invalidated", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("_snapflow_data_block_log", "invalidated")
    # ### end Alembic commands ###
