"""Time out nullable

Revision ID: d9d9a9f028a0
Revises: dc54046cb677
Create Date: 2021-06-20 18:52:53.396230

"""
import snapflow
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d9d9a9f028a0"
down_revision = "dc54046cb677"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
