"""Time out

Revision ID: dc54046cb677
Revises: 83486b160cf0
Create Date: 2021-06-18 10:09:55.924544

"""
import snapflow
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dc54046cb677"
down_revision = "83486b160cf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "_snapflow_data_function_log",
        sa.Column("timed_out", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("_snapflow_data_function_log", "timed_out")
    # ### end Alembic commands ###
