"""Changes for dcp

Revision ID: fcfed9f36be4
Revises: 5b7f90e7bfdb
Create Date: 2021-04-11 20:35:59.334778

"""
import snapflow
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fcfed9f36be4"
down_revision = "5b7f90e7bfdb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "_snapflow_data_block_log",
        sa.Column("stream_name", sa.String(length=128), nullable=True),
    )
    with op.batch_alter_table("_snapflow_snap_log") as batch_op:
        batch_op.alter_column(
            "runtime_url",
            existing_type=sa.VARCHAR(length=128),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "_snapflow_snap_log",
        "runtime_url",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
    )
    op.drop_column("_snapflow_data_block_log", "stream_name")
    # ### end Alembic commands ###
