"""Initial

Revision ID: 03a220f6e38f
Revises: 
Create Date: 2021-08-25 13:59:33.413023

"""
from alembic import op
import sqlalchemy as sa
import basis


# revision identifiers, used by Alembic.
revision = '03a220f6e38f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_basis_block_metadata',
    sa.Column('env_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('inferred_schema_key', sa.String(length=128), nullable=True),
    sa.Column('nominal_schema_key', sa.String(length=128), nullable=True),
    sa.Column('realized_schema_key', sa.String(length=128), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('created_by_node_key', sa.String(length=128), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_basis_execution_log',
    sa.Column('env_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_key', sa.String(length=128), nullable=False),
    sa.Column('node_start_state', sa.JSON(), nullable=True),
    sa.Column('node_end_state', sa.JSON(), nullable=True),
    sa.Column('function_key', sa.String(length=128), nullable=False),
    sa.Column('function_params', sa.JSON(), nullable=True),
    sa.Column('runtime_url', sa.String(length=128), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_basis_generated_schema',
    sa.Column('env_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('_basis_stream_state',
    sa.Column('env_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_key', sa.String(length=128), nullable=True),
    sa.Column('stream_name', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.Enum('INPUT', 'OUTPUT', name='direction', native_enum=False), nullable=False),
    sa.Column('first_processed_block_id', sa.String(length=128), nullable=True),
    sa.Column('latest_processed_block_id', sa.String(length=128), nullable=True),
    sa.Column('latest_processed_at', sa.DateTime(), nullable=True),
    sa.Column('blocks_processed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_basis_stored_block_metadata',
    sa.Column('env_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('block_id', sa.String(length=128), nullable=False),
    sa.Column('storage_url', sa.String(length=128), nullable=False),
    sa.Column('data_format', basis.core.persistence.base.DataFormatType(length=128), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['_basis_block_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_basis_alias',
    sa.Column('env_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('storage_url', sa.String(length=128), nullable=True),
    sa.Column('block_id', sa.String(length=128), nullable=False),
    sa.Column('stored_block_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['_basis_block_metadata.id'], ),
    sa.ForeignKeyConstraint(['stored_block_id'], ['_basis_stored_block_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env_id', 'name', 'storage_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_basis_alias')
    op.drop_table('_basis_stored_block_metadata')
    op.drop_table('_basis_stream_state')
    op.drop_table('_basis_generated_schema')
    op.drop_table('_basis_execution_log')
    op.drop_table('_basis_block_metadata')
    # ### end Alembic commands ###
